In [1]:
import torch

In [4]:
tensor1 = torch.randint(0, 3, (1, 1, 4, 4, 4))
tensor1 = tensor1.float()

print(tensor1.shape)
print(tensor1)

torch.Size([1, 1, 4, 4, 4])
tensor([[[[[1., 2., 1., 1.],
           [1., 2., 2., 1.],
           [2., 1., 1., 1.],
           [2., 1., 2., 1.]],

          [[0., 2., 0., 1.],
           [2., 0., 1., 0.],
           [2., 2., 1., 0.],
           [2., 2., 2., 1.]],

          [[0., 2., 2., 2.],
           [1., 1., 2., 2.],
           [1., 0., 1., 1.],
           [1., 0., 2., 2.]],

          [[0., 2., 1., 1.],
           [2., 2., 2., 1.],
           [0., 1., 2., 1.],
           [2., 0., 2., 2.]]]]])


In [5]:
conv1 = torch.nn.Conv3d(in_channels=1, out_channels=1, kernel_size=2, stride=1, padding=0)

print(conv1.weight)
print(conv1.bias)

Parameter containing:
tensor([[[[[ 0.1529,  0.2800],
           [ 0.2304,  0.2916]],

          [[ 0.1749, -0.3370],
           [-0.2940,  0.1944]]]]], requires_grad=True)
Parameter containing:
tensor([-0.1909], requires_grad=True)


In [6]:
F1 = conv1(tensor1)

print(F1)

tensor([[[[[ 0.0737,  1.9833,  0.3635],
           [ 1.4252,  0.4664,  0.7980],
           [ 0.6241,  0.8694,  0.7759]],

          [[ 0.0563,  0.1772, -0.2038],
           [ 0.7030,  0.5369, -0.2314],
           [ 1.6000,  1.4909,  0.3533]],

          [[ 0.0180,  1.3023,  1.1634],
           [ 0.3426,  0.5843,  0.8163],
           [-0.7325,  0.5620,  1.0998]]]]], grad_fn=<ConvolutionBackward0>)


In [7]:
conv2 = torch.nn.Conv3d(in_channels=1, out_channels=2, kernel_size=2, stride=1, padding=0)

print(conv2.weight)
print(conv2.bias)

Parameter containing:
tensor([[[[[-0.1647, -0.0044],
           [ 0.0772, -0.3414]],

          [[-0.3340, -0.2895],
           [ 0.2919, -0.2541]]]],



        [[[[-0.3024, -0.2919],
           [ 0.2777,  0.0414]],

          [[ 0.3365,  0.0342],
           [ 0.1437, -0.0883]]]]], requires_grad=True)
Parameter containing:
tensor([0.3017, 0.0854], requires_grad=True)


In [8]:
F2 = conv2(tensor1)

print(F2)

tensor([[[[[-4.7267e-01, -1.4826e+00, -5.2085e-02],
           [-6.5129e-01, -2.6059e-01, -3.3847e-01],
           [-1.3906e+00, -1.3549e+00, -5.8770e-02]],

          [[-9.4036e-02, -1.8323e+00, -7.9696e-01],
           [-8.8771e-01, -1.0568e+00, -9.9504e-01],
           [-6.0710e-01, -1.3582e+00, -5.9789e-01]],

          [[-4.7474e-01, -1.5240e+00, -8.5878e-01],
           [-1.2914e+00, -1.6765e+00, -9.2861e-01],
           [ 5.0843e-01, -1.8066e+00, -1.2777e+00]]],


         [[[-8.4652e-02,  4.1141e-01,  2.6567e-01],
           [ 5.7961e-01, -5.5089e-01, -1.2051e-02],
           [ 6.3750e-01,  6.6939e-01,  6.2337e-01]],

          [[ 1.8060e-01,  2.3035e-01,  9.2321e-01],
           [ 6.3307e-01,  7.0664e-01,  8.5736e-01],
           [ 1.5067e-02, -3.1573e-01,  8.6112e-01]],

          [[-3.1801e-04,  7.5107e-02,  1.0463e-01],
           [ 4.2173e-01, -5.1107e-02,  1.2208e-01],
           [ 3.8228e-01,  1.0433e-01,  9.4706e-01]]]]],
       grad_fn=<ConvolutionBackward0>)


In [13]:
input_t = torch.randint(0, 2, (1, 1, 32, 32, 32))  # [0, 2)
input_t = input_t.float()
print(input_t.shape)

torch.Size([1, 1, 32, 32, 32])


In [52]:
conv1 = torch.nn.Conv3d(in_channels=1, out_channels=2, kernel_size=3, stride=1, padding=0, dilation=2)
out_conv1 = conv1(input_t)

print(out_conv1.shape)

torch.Size([1, 2, 28, 28, 28])


In [53]:
conv2 = torch.nn.Conv3d(in_channels=2, out_channels=4, kernel_size=3, stride=1, padding=0, dilation=2)
out_conv2 = conv2(out_conv1)

print(out_conv2.shape)


torch.Size([1, 4, 24, 24, 24])


In [64]:
conv3 = torch.nn.Conv3d(in_channels=4, out_channels=8, kernel_size=3, stride=1, padding=0, dilation=2)
out_conv3 = conv3(out_conv2)

print(out_conv3.shape)

torch.Size([1, 8, 20, 20, 20])


In [65]:
conv4 = torch.nn.Conv3d(in_channels=8, out_channels=16, kernel_size=3, stride=1, padding=0, dilation=2)
out_conv4 = conv4(out_conv3)

print(out_conv4.shape)

torch.Size([1, 16, 16, 16, 16])


In [66]:
conv2d_input_t = out_conv4.reshape(out_conv4.shape[0], out_conv4.shape[1], 64, 64)

print(conv2d_input_t.shape)

torch.Size([1, 16, 64, 64])


In [77]:
class_head_conv1 = torch.nn.Conv2d(in_channels=16, out_channels=32, kernel_size=3, stride=2, padding=1, dilation=1)
class_head_out1 = class_head_conv1(conv2d_input_t)

print(class_head_out1.shape)

torch.Size([1, 32, 32, 32])


In [82]:
num_class = 4

class_head_conv2 = torch.nn.Conv2d(in_channels=32, out_channels=num_class, kernel_size=3, stride=2, padding=1, dilation=1)
class_head_out2 = class_head_conv2(class_head_out1)

print(class_head_out2.shape)

torch.Size([1, 4, 16, 16])


In [81]:
out_class_head = class_head_out2.reshape(class_head_out2.shape[0], num_class, -1)
print(out_class_head.shape)

# out_class_head = out_class_head.reshape(-1, )

torch.Size([1, 4, 8192])


In [76]:
conv8 = torch.nn.Conv2d(in_channels=32, out_channels=64, kernel_size=3, stride=2, padding=1, dilation=1)
out_conv8 = conv8(out_conv7)

print(out_conv8.shape)

torch.Size([1, 64, 16, 16])


In [ ]:
conv9 = 

In [74]:
a = torch.rand((1, 56,56))
c = torch.nn.Conv2d(1, 2, 3, 2, 1)
print(c(a).shape)

torch.Size([2, 28, 28])
